services:
  postgres:
    image: 'postgres:latest'
    container_name: 'pair-challenge-postgres'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=my_user'
    ports:
      - '5422:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: pairs-challenge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2184:2181"

  redis:
    image: redis/redis-stack:latest
    container_name: 'redis-container'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
      - /Users/danaradaev/IdeaProjects/PairsChallenge/redis.conf
    command: redis-server --requirepass your_secure_password
    environment:
      - REDIS_PASSWORD=secret

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: pairs-challenge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1